services:
  api:
    build:
      context: .
      dockerfile: docker/DockerFile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    working_dir: /app
    volumes:
      - .:/app
    command: sleep infinity

  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7

volumes:
  pgdata:
