FROM golang:1.25.6-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o golang-e-commerce-api cmd/api/main.go


FROM alpine:latest
WORKDIR /app

COPY --from=builder /app/golang-e-commerce-api .
COPY --from=builder /app/migrations ./migrations
CMD ["./golang-e-commerce-api"]
