FROM golang:1.25.6-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o golang-e-commerce-api cmd/api/main.go


FROM alpine:latest
WORKDIR /app

RUN adduser -D appuser

COPY --from=builder /app/golang-e-commerce-api .
COPY --from=builder /app/migrations ./migrations

EXPOSE 8080
USER appuser

CMD ["./golang-e-commerce-api"]