FROM golang:1.25.6-alpine AS builder
WORKDIR /app
COPY g.mod go.sum ./
RUN g.mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o app cmd/api/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/app .
COPY .env .
EXPOSE 8080
CMD ["./app"]